// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package bridge

import (
	"database/sql"

	"github.com/google/uuid"
)

type Account struct {
	ID        uuid.UUID
	Email     string
	Password  string
	Hash      string
	IsDeleted bool
	RoleID    uuid.UUID
}

type ResetPassword struct {
	ID        uuid.UUID
	Email     string
	Token     string
	CreatedAt sql.NullTime
}

type Role struct {
	ID   uuid.UUID
	Name string
}

type Task struct {
	ID          uuid.UUID
	Title       string
	Description sql.NullString
	Status      string
	CreatedAt   sql.NullTime
	UpdatedAt   sql.NullTime
	DeletedAt   sql.NullTime
}
